name: Build and Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main
jobs:
  deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install make wget
    - name: Install quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb
        sudo dpkg -i ./quarto-1.3.361-linux-amd64.deb
    - name: Compile
      run: make
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

